#!/bin/bash
# Before running this, see the directions at:
#   http://lucasbardella.com/blog/2010/02/hosting-your-sphinx-docs-in-github
# Dependencies:
# sphinx
# numpydocs
BUILDDIR=/home/ibackus/docs/diskpy
HTMLDIR=$BUILDDIR/html
rm -rf doc
mkdir doc
cp docconf.py doc/conf.py
sphinx-apidoc -d 4 -A "Isaac Backus" -F -o doc ../diskpy
cd doc
make html BUILDDIR=$BUILDDIR
cd $HTMLDIR
echo > .nojekyll
git add -A
git commit -a -m "Updating docs"
git push origin gh-pages
