#!/bin/bash
# Before running this:
#   - Set BUILDDIR below
#   - see:
#   http://lucasbardella.com/blog/2010/02/hosting-your-sphinx-docs-in-github
# Dependencies:
# sphinx
# numpydocs
# 
# DIRECTIONS:
#	1) cd into directory containing this
#	2) Build the docs with:
#		>>> ./builddocs
#	3) Verify that it's okay, then publish to github:
#		>>> ./publishdocs
BUILDDIR=/home/ibackus/docs/diskpy
HTMLDIR=$BUILDDIR/html
cd diskpy/doc
make html BUILDDIR=$BUILDDIR
cd $HTMLDIR
echo > .nojekyll
git add -A
git commit -a -m "Updating docs"
git push origin gh-pages

